-- 게시판
DROP TABLE IF EXISTS BOARD RESTRICT;

-- 게시판관리자
DROP TABLE IF EXISTS MANAGER RESTRICT;

-- 게시물
DROP TABLE IF EXISTS ARTICLE RESTRICT;

-- 사용자
DROP TABLE IF EXISTS USER RESTRICT;

-- 댓글
DROP TABLE IF EXISTS COMMENT RESTRICT;

-- 게시판
CREATE TABLE BOARD (
	BOARD_NO   INTEGER      NOT NULL COMMENT '게시판번호', -- 게시판번호
	BOARD_NAME VARCHAR(200) NOT NULL COMMENT '게시판명칭' -- 게시판명칭
)
COMMENT '게시판';

-- 게시판
ALTER TABLE BOARD
	ADD CONSTRAINT PK_BOARD -- 게시판 기본키
		PRIMARY KEY (
			BOARD_NO -- 게시판번호
		);

ALTER TABLE BOARD
	MODIFY COLUMN BOARD_NO INTEGER NOT NULL AUTO_INCREMENT COMMENT '게시판번호';

-- 게시판관리자
CREATE TABLE MANAGER (
	FK_BOARD_NO INTEGER     NOT NULL COMMENT '게시판번호', -- 게시판번호
	FK_USER_ID  VARCHAR(20) NOT NULL COMMENT '관리자ID' -- 관리자ID
)
COMMENT '게시판관리자';

-- 게시판관리자
ALTER TABLE MANAGER
	ADD CONSTRAINT PK_MANAGER -- 게시판관리자 기본키
		PRIMARY KEY (
			FK_BOARD_NO, -- 게시판번호
			FK_USER_ID   -- 관리자ID
		);

-- 게시물
CREATE TABLE ARTICLE (
	ARTICLE_NO  INTEGER      NOT NULL COMMENT '게시물번호', -- 게시물번호
	SUBJECT     VARCHAR(300) NOT NULL COMMENT '게시물제목', -- 게시물제목
	CONTENT     TEXT         NULL     COMMENT '게시물본문', -- 게시물본문
	AUTHOR_ID   VARCHAR(20)  NULL     COMMENT '작성자ID', -- 작성자ID
	AUTHOR_NAME VARCHAR(50)  NOT NULL COMMENT '작성자명', -- 작성자명
	REG_DATE    DATETIME     NOT NULL COMMENT '등록일시', -- 등록일시
	FK_BOARD_NO INTEGER      NOT NULL COMMENT '게시판번호' -- 게시판번호
)
COMMENT '게시물';

-- 게시물
ALTER TABLE ARTICLE
	ADD CONSTRAINT PK_ARTICLE -- 게시물 기본키
		PRIMARY KEY (
			ARTICLE_NO -- 게시물번호
		);

ALTER TABLE ARTICLE
	MODIFY COLUMN ARTICLE_NO INTEGER NOT NULL AUTO_INCREMENT COMMENT '게시물번호';

-- 사용자
CREATE TABLE USER (
	USER_ID   VARCHAR(20) NOT NULL COMMENT '사용자ID', -- 사용자ID
	PASSWORD  VARCHAR(20) NOT NULL COMMENT '패스워드', -- 패스워드
	USER_NAME VARCHAR(50) NOT NULL COMMENT '사용자이름', -- 사용자이름
	EMAIL     VARCHAR(40) NULL     COMMENT '이메일' -- 이메일
)
COMMENT '사용자';

-- 사용자
ALTER TABLE USER
	ADD CONSTRAINT PK_USER -- 사용자 기본키
		PRIMARY KEY (
			USER_ID -- 사용자ID
		);

-- 댓글
CREATE TABLE COMMENT (
	COMMENT_NO     INTEGER      NOT NULL COMMENT '댓글번호', -- 댓글번호
	COMMENT        VARCHAR(500) NOT NULL COMMENT '댓글내용', -- 댓글내용
	COMMENTER_ID   VARCHAR(20)  NULL     COMMENT '작성자ID', -- 작성자ID
	COMMENTER_NAME VARCHAR(50)  NOT NULL COMMENT '작성자명', -- 작성자명
	REG_DATE       DATETIME     NOT NULL COMMENT '등록일시', -- 등록일시
	FK_ARTICLE_NO  INTEGER      NOT NULL COMMENT '게시물번호', -- 게시물번호
	FK_BOARD_NO    INTEGER      NOT NULL COMMENT '게시판번호' -- 게시판번호
)
COMMENT '댓글';

-- 댓글
ALTER TABLE COMMENT
	ADD CONSTRAINT PK_COMMENT -- 댓글 기본키
		PRIMARY KEY (
			COMMENT_NO -- 댓글번호
		);

ALTER TABLE COMMENT
	MODIFY COLUMN COMMENT_NO INTEGER NOT NULL AUTO_INCREMENT COMMENT '댓글번호';